# `pydantic_ai.exceptions`

::: pydantic_ai.exceptions
